# Generated by Django 5.1.6 on 2025-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='otp',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور'),
        ),
    ]
